version: '3.8'

services:
  # Cassandra Database
  cassandra:
    image: cassandra:latest
    container_name: kong-database
    ports:
      - "7000:7000"
    restart: always
    volumes:
      - ./cassandra-vol:/var/lib/cassandra

  # Kong API Gateway
  kong:
    image: kong:latest
    restart: always
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl

    ports:
      - "80:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

    depends_on:
      - cassandra

  # Konga GUI
  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    environment:
      DB_ADAPTER: cassandra
      DB_URI: cassandra://kong:kong@kong-database:9042/konga
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
    volumes:
      - ./kong-vol:/app/kongadata
