version: '3'

services:
  # Postgres Database
  kong_database:
    image: postgres:latest
    restart: always
    container_name: kong-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 10s
      retries: 10

  # Kong database migrations
  kong-migrations:
    image: kong:latest
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_PG_HOST=kong_database
    depends_on:
      - kong_database

  # Kong API Gateway
  kong:
    image: kong:latest
    restart: always
    environment:
      KONG_PG_HOST: kong_database
      KONG_PROXY_LISTEN: 0.0.0.0:80
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001

    ports:
      - "80:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

    depends_on:
      - kong-migrations
      - kong_database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 10s
      timeout: 5s
      retries: 15

  # Konga GUI
  konga:
    image: pantsel/konga:next
    container_name: konga
    restart: always
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong_database
      DB_USER: kong
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_DATABASE: konga_db
      NODE_ENV: production
    depends_on:
      - kong_database
    ports:
      - "1337:1337"
