version: '3.8'

volumes:
  kong-data: {}

networks:
  kong-net: {}

services:
  # Cassandra Database
  kong-database:
    image: cassandra:latest
    container_name: kong-cassandra
    restart: on-failure
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "cqlsh", "--execute", "exit"]
      interval: 30s
      timeout: 30s
      retries: 3

  # Kong API Gateway
  kong:
    image: kong:latest
    restart: on-failure
    networks:
      - kong-net
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_CASSANDRA_KEYSPACE: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    ports:
      - "80:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  # Kong Preparation for Cassandra
  kong-prepare:
    image: pantsel/konga:latest
    command: ["-c", "prepare", "-a", "cassandra", "-u", "cassandra://kong:kong@kong-database:9042/konga"]
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  # Konga GUI
  konga:
    image: pantsel/konga:latest
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: cassandra
      DB_URI: cassandra://kong:kong@kong-database:9042/konga
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
